<?php 
return [
 'config_meta_tag_keywords' => ''  ,
 'config_fb_url' => 'https://www.facebook.com/'  ,
 'config_linkedin_url' => 'https://www.linkedin.com/'  ,
 'config_twitter_url' => 'https://twitter.com/login?lang=en'  ,
 'config_youtube_url' => 'https://www.youtube.com/channel/UCiWzLziMAOk-oB0pig8TkEg/'  ,
 'config_mail_engine' => 'smtp'  ,
 'config_insta_url' => 'https://www.instagram.com/'  ,
 'config_smtp_username' => 'otrixapp@gmail.in'  ,
 'config_smtp_hostname' => 'smtp.googlemail.ddd'  ,
 'config_smtp_password' => 'abcdabcdefgefg'  ,
 'config_smtp_timeout' => '25'  ,
 'config_smtp_port' => '25'  ,
 'config_store_image' => '1726694590WhatsApp_Image_2024-09-15_at_2.54.48_PM-removebg-preview.png'  ,
 'config_alert_mail' => 'Register,Orders'  ,
 'config_icon_image' => '168941197910.png'  ,
 'config_currency' => 'KWD'  ,
 'config_fax' => '101010'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'hello@dhsol.net'  ,
 'config_geocode' => '54654'  ,
 'config_store_owner' => 'Famme Flora'  ,
 'config_address' => 'No address'  ,
 'config_store_name' => 'Famme Flora'  ,
 'config_meta_tag_description' => ''  ,
 'config_meta_title' => 'Famme Flora'  ,
 'config_web_bg' => '#626ABB'  ,
 'config_currency' => 'KWD'  ,
 'config_fax' => '101010'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'hello@dhsol.net'  ,
 'config_geocode' => '54654'  ,
 'config_address' => 'No address'  ,
 'config_store_owner' => 'Famme Flora'  ,
 'config_store_name' => 'Famme Flora'  ,
 'config_encryption' => 'tls'  ,
 'config_from' => 'otrix@mail.in'  ,
 'config_from_name' => 'dasd'  ,
 'config_signup_discount_status' => '0'  ,
 'config_signup_discount' => '15'  ,
  "config_signup_discount_text" =>  "{\"4\":\"Sign Up  And  _DISCOUNT_  special discount on your first order\",\"5\":\"\\u0627\\u0634\\u062a\\u0631\\u0643 \\u0648 _DISCOUNT_ \\u062e\\u0635\\u0645 \\u062e\\u0627\\u0635 \\u0639\\u0644\\u0649 \\u0637\\u0644\\u0628\\u0643 \\u0627\\u0644\\u0623\\u0648\\u0644\"}",  'config_layout' => 'otrixlayout'  ,
 'config_twilio_sid' => 'AC03edc552fb'  ,
 'config_twilio_token' => '721bd6d11442ced'  ,
 'config_twilio_from' => '+17622'  ,
 'config_alert_sms' => 'Register,Orders'  ,
 'config_registerSMSContent' => 'Thank you for register on otrixcommerce'  ,
 'config_talk_to_expert' => '{\"4\":\"Hello\",\"5\":\"\\u0645\\u0631\\u062d\\u0628\\u064b\\u0627\"}'  ,
  "config_talk_to_expert" =>  "{\"4\":\"Hello\",\"5\":\"\\u0645\\u0631\\u062d\\u0628\\u064b\\u0627\"}",  'config_talk_to_expert_mobile' => '0000000'  ,
 'config_social_status' => '1'  ,
 'config_accept_terms_before_order' => '1'  ,
];
